SET DIRETORIO=C:\MicroSO\trunk\LABS\COMPILE\vfd21-080206\
REG QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /v vfd
IF %ERRORLEVEL% EQU 0 GOTO EXISTS
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /v Vfd /t REG_SZ /d %DIRETORIO%install.vbs
%DIRETORIO%VFD.EXE INSTALL
:EXISTS
%DIRETORIO%VFD.EXE START
%DIRETORIO%VFD.EXE OPEN /RAM /1.44