..\ML.EXE /c /AT c0t.asm
..\ML.EXE /c /AT STDIO.ASM
IF EXIST STDIO.OBJ REN STDIO.OBJ STDIOA.OBJ
..\TCC.EXE -1 -K- -k -ms -N- -c -w- -v -y *.c
..\LINK16.EXE /TINY c0t.OBJ MAIN.OBJ STDIO.OBJ STDIOA.OBJ, MAIN.COM,,,,
DEL *.OBJ *.MAP *.BAK
PAUSE