SET PATH=C:\MSVC\BIN;C:\MASM615\BIN;C:\PROGRAM FILES\QEMU;C:\PROGRAM FILES\WINIMAGE;
SET INCLUDE=C:\MSVC\INCLUDE
SET LIB=C:\MSVC\LIB
SET IMAGE="C:\PROGRAM FILES\QEMU\IMAGES\MSDOS\MSDOS.IMG"

CL /I %INCLUDE% /c /G3 /Gy /W1 /Zi /AS /D "_DEBUG" /D "_DOS" /FR /Fd"MAIN.PDB" *.C
rem CL /c /nologo /G2 /Gy /W1 /Zi /AM /Od /D "_DEBUG" /D "_DOS" /FR /Fd"MAIN.PDB" *.C
ML /c *.ASM

LINK /NOLOGO /NOI /STACK:5120 /ONERROR:NOEXE /CO MAIN.OBJ READCFG.OBJ PRINTDW.OBJ RTL8139.OBJ IODW.OBJ, MAIN.EXE,,,,

setlocal
:PROMPT
@ECHO OFF
SET /P AREYOUSURE=EXECUTAR (Y/[N])?
IF /I "%AREYOUSURE%" NEQ "Y" GOTO END
PUSHD %cd%
WINIMAGE %IMAGE% /I /Q /H %cd%\MAIN.EXE
WINIMAGE %IMAGE% /I /Q /H %cd%\MAIN.CFG
CD "C:\PROGRAM FILES\QEMU\IMAGES\MSDOS"
MSDOS
:END
CLS
endlocal